# Generated by Django 3.1.5 on 2021-02-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='meetingname',
            field=models.CharField(default='replacename', max_length=255),
            preserve_default=False,
        ),
    ]
